### ISSUE TITLE
Issue with Fluid Wagon Color Mask

### ISSUE THREAD

**Issue by Quezler** [shanemadden/factorio-train-scaling#5]
> maybe related to #2 somehow?

![Screen Shot 2020-07-12 at 19 06 28](https://user-images.githubusercontent.com/3179271/87252391-f2f9e280-c472-11ea-91fc-873ae21aa7e1.png)

so on the same multiplayer server where i ran into #4 i also had an issue i didn't manage to debug yet, so i left it.

all i managed to find to this specific issue is where it returned false when it happened:
https://github.com/shanemadden/factorio-train-scaling/blob/master/control.lua#L244

today i finally played with my modlist checkboxes to enable/disable one after the other to see what causes/fixes it,
and apparently this mod is to blame somehow: https://mods.factorio.com/mod/FluidWagonColorMask
with that enabled, it fails 100% of the time, and with it disabled 0% of the time, for both item & fluid wagons.

currently my brain is fried so i'll just leave this here for now, hopefully this can be of some help ❤️

**Comment by Quezler** [comment]
also worth noting that each time this fails the locomotive & wagons are refunded, but not the fuel 🔥

**Comment by Ashotep** [comment]
I can confirm that it is a fluid wagon color issue.  I use [https://mods.factorio.com/mod/Automatic_Train_Painter](url).  When I disable the option to color the fluid wagons it worked just fine.  Easy enough thing to disable on my side to get this working.

**Comment by Quezler** [comment]
interesting, wasn't aware disabeling the checkbox in that main mod would stop the issue from occurring, though of course i'd rather keep this issue open since we want them all to be colored 🤔

**Comment by Ashotep** [comment]
I suspect it errors out when it attempts to apply the color mask to entities that do not have that option in base game.  I'm not familiar enough with how both mods work to suggest a fix.

Maybe if the color mask was ignored and let the other mod apply the color when the new train picks up mats.

**Comment by shanemadden** [comment]
Tricky. The best solution/idea I have is to have the carriage comparison not worry about color when validating that it built the right train - I'm trying to think if this'll cause any other weirdness, but I think it should be ok. I'll get a version up with that changed shortly and we'll see if they behave together better.

**Comment by Quezler** [comment]
thx ❤️
